name: Build
on:
    workflow_dispatch: {}
# develop pushes and repository_dispatch handled in build_develop.yaml
env:
    # These must be set for fetchdep.sh to get the right branch
    REPOSITORY: ${{ github.repository }}
    PR_NUMBER: ${{ github.event.pull_request.number }}
jobs:
    build:
        name: "Build"
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3

            - uses: actions/setup-node@v3
              with:
                  cache: "yarn"

            - name: Authenticate with GitHub Packages
              uses: docker/login-action@v1
              with:
                  registry: docker.pkg.github.com
                  username: ${{ github.repository_owner }}
                  password: ${{ secrets.PAT }}

            - name: Install Dependencies
              run: "./scripts/layered.sh"

            - name: Build
              run: "yarn build"
