name: Static Analysis
on:
    pull_request: {}
    push:
        branches: [develop, master]
    repository_dispatch:
        types: [element-web-notify]
env:
    # These must be set for fetchdep.sh to get the right branch
    REPOSITORY: ${{ github.repository }}
    PR_NUMBER: ${{ github.event.pull_request.number }}
jobs:
    ts_lint:
        name: "Typescript Syntax Check"
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3

            - uses: actions/setup-node@v3
              with:
                  cache: "yarn"

            - name: Install Dependencies
              run: "./scripts/layered.sh"

            - name: Typecheck
              run: "yarn run lint:types"

    tsc-strict:
        name: Typescript Strict Error Checker
        if: github.event_name == 'pull_request'
        runs-on: ubuntu-latest
        permissions:
            pull-requests: read
            checks: write
        steps:
            - uses: actions/checkout@v3

            - name: Install Deps
              run: "scripts/layered.sh"

            - name: Get diff lines
              id: diff
              uses: Equip-Collaboration/diff-line-numbers@df70b4b83e05105c15f20dc6cc61f1463411b2a6 # v1.0.0
              with:
                  include: '["\\.tsx?$"]'

            - name: Detecting files changed
              id: files
              uses: futuratrepadeira/changed-files@96d5fd702a6479d573287ef07381ad59acc390ed # v4.0.0
              with:
                  repo-token: ${{ secrets.GITHUB_TOKEN }}
                  pattern: '^.*\.tsx?$'

            - uses: t3chguy/typescript-check-action@main
              with:
                  repo-token: ${{ secrets.GITHUB_TOKEN }}
                  use-check: false
                  check-fail-mode: added
                  output-behaviour: annotate
                  ts-extra-args: "--strict --noImplicitAny"
                  files-changed: ${{ steps.files.outputs.files_updated }}
                  files-added: ${{ steps.files.outputs.files_created }}
                  files-deleted: ${{ steps.files.outputs.files_deleted }}
                  line-numbers: ${{ steps.diff.outputs.lineNumbers }}

    i18n_lint:
        name: "i18n Check"
        uses: matrix-org/matrix-react-sdk/.github/workflows/i18n_check.yml@develop

    js_lint:
        name: "ESLint"
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3

            - uses: actions/setup-node@v3
              with:
                  cache: "yarn"

            # Does not need branch matching as only analyses this layer
            - name: Install Deps
              run: "yarn install --pure-lockfile"

            - name: Run Linter
              run: "yarn run lint:js"

    style_lint:
        name: "Style Lint"
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3

            - uses: actions/setup-node@v3
              with:
                  cache: "yarn"

            # Needs branch matching as it inherits .stylelintrc.js from matrix-react-sdk
            - name: Install Dependencies
              run: "./scripts/layered.sh"

            - name: Run Linter
              run: "yarn run lint:style"

    analyse_dead_code:
        name: "Analyse Dead Code"
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3

            - uses: actions/setup-node@v3
              with:
                  cache: "yarn"

            - name: Install Deps
              run: "scripts/layered.sh"

            - name: Dead Code Analysis
              run: "yarn run analyse:unused-exports"
